IMAGE_NAME=loadimpact/pgbouncer
IMAGE_VERSION=1.15.0

docker:
	docker build -t $(IMAGE_NAME):$(IMAGE_VERSION) .
	docker tag $(IMAGE_NAME):$(IMAGE_VERSION) $(IMAGE_NAME):latest

push:
	docker push $(IMAGE_NAME):$(IMAGE_VERSION)
	docker push $(IMAGE_NAME):latest

.PHONY: test
test:
	rm -f ./test/*
	TEST=1 \
	POOL_MODE=transaction \
	AUTH_TYPE=trust \
	SERVER_RESET_QUERY="DISCARD ALL" \
	MAX_CLIENT_CONN=1000 \
	DEFAULT_POOL_SIZE=50 \
	LISTEN_BACKLOG=4096 \
	METRICS_DB_NAME=metrics \
	METRICS_DB_HOST=10.10.10.10 \
	METRICS_DB_PORT=5432 \
	METRICS_DB_USER=user \
	METRICS_DB_PASSWORD=secret \
	METRICS_REPLICA_DB_NAME=metrics_replica \
	METRICS_REPLICA_DB_HOST=10.10.10.10 \
	METRICS_REPLICA_DB_PORT=5432 \
	METRICS_REPLICA_DB_USER=user \
	METRICS_REPLICA_DB_PASSWORD=secret \
	LOADIMPACT_DB_NAME=loadimpact \
	LOADIMPACT_DB_HOST=10.10.10.10 \
	LOADIMPACT_DB_PORT=5432 \
	LOADIMPACT_DB_USER=user \
	LOADIMPACT_DB_PASSWORD=secret \
	MONIT_USER=datadog \
	MONIT_PASSWORD=secret \
	STATS_USERS=datadog \
	TCP_KEEPALIVE=1 \
	TCP_KEEPIDLE=120 \
	CLIENT_ENCODING=UNICODE \
	./entrypoint.sh

